version: "3"

services:
  web:
    restart: always
    build: .
    expose:
      - ${WEB_PORT}
    volumes:
      - ./web:/home/web
      - web-data:/home/web/data
    env_file: .env
    command: /bin/sh -c 'python manage.py collectstatic --noinput; python manage.py makemigrations --noinput; python manage.py migrate; gunicorn --chdir ./web/ web.wsgi:application --bind 0.0.0.0:${WEB_PORT} --reload;'
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    restart: always
    build: ./web/nginx
    ports:
      - "${WEB_PORT}:80"
    environment:
      - WEB_PORT=${WEB_PORT}
    volumes:
      - ./web/static:/home/web/static
      - /opt/upload:/opt/upload
    depends_on:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    restart: always
    container_name: redis
    image: redis:alpine
    ports:
      - "6381:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  celery_web_tasks_bot:
    build: .
    restart: always
    command: celery -A web.celery_utils worker --beat -l info 
    env_file: .env
    depends_on:
      - web
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  celery_editor_bot:
    build: ./compressorbot
    restart: always
    command: celery -A utils.tasks worker -l info
    env_file: .env
    depends_on:
      - web
      - redis
      
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  compressorbot:
    build: ./compressorbot
    restart: always
    container_name: ${BOT_NAME}
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - web
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  redis-data:
  web-data:
